-- DROP SCHEMA dev;

-- CREATE SCHEMA dev AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE dev.auth_group_id_seq;

CREATE SEQUENCE dev.auth_group_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.auth_group_permissions_id_seq;

CREATE SEQUENCE dev.auth_group_permissions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.auth_permission_id_seq;

CREATE SEQUENCE dev.auth_permission_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.django_admin_log_id_seq;

CREATE SEQUENCE dev.django_admin_log_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.django_content_type_id_seq;

CREATE SEQUENCE dev.django_content_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.django_migrations_id_seq;

CREATE SEQUENCE dev.django_migrations_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.silk_profile_id_seq;

CREATE SEQUENCE dev.silk_profile_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.silk_profile_queries_id_seq;

CREATE SEQUENCE dev.silk_profile_queries_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE dev.silk_sqlquery_id_seq;

CREATE SEQUENCE dev.silk_sqlquery_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- dev.accounts_customuser definition

-- Drop table

-- DROP TABLE dev.accounts_customuser;

CREATE TABLE dev.accounts_customuser (
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	id uuid NOT NULL,
	username varchar(20) NOT NULL,
	email varchar(254) NOT NULL,
	is_active bool NOT NULL,
	is_admin bool NOT NULL,
	CONSTRAINT accounts_customuser_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_customuser_username_key UNIQUE (username)
);
CREATE INDEX accounts_customuser_username_722f3555_like ON dev.accounts_customuser USING btree (username varchar_pattern_ops);


-- dev.auth_group definition

-- Drop table

-- DROP TABLE dev.auth_group;

CREATE TABLE dev.auth_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON dev.auth_group USING btree (name varchar_pattern_ops);


-- dev.django_content_type definition

-- Drop table

-- DROP TABLE dev.django_content_type;

CREATE TABLE dev.django_content_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);


-- dev.django_migrations definition

-- Drop table

-- DROP TABLE dev.django_migrations;

CREATE TABLE dev.django_migrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);


-- dev.django_session definition

-- Drop table

-- DROP TABLE dev.django_session;

CREATE TABLE dev.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
CREATE INDEX django_session_expire_date_a5c62663 ON dev.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON dev.django_session USING btree (session_key varchar_pattern_ops);


-- dev.silk_request definition

-- Drop table

-- DROP TABLE dev.silk_request;

CREATE TABLE dev.silk_request (
	id varchar(36) NOT NULL,
	"path" varchar(190) NOT NULL,
	query_params text NOT NULL,
	raw_body text NOT NULL,
	body text NOT NULL,
	"method" varchar(10) NOT NULL,
	start_time timestamptz NOT NULL,
	view_name varchar(190) NULL,
	end_time timestamptz NULL,
	time_taken float8 NULL,
	encoded_headers text NOT NULL,
	meta_time float8 NULL,
	meta_num_queries int4 NULL,
	meta_time_spent_queries float8 NULL,
	pyprofile text NOT NULL,
	num_sql_queries int4 NOT NULL,
	prof_file varchar(300) NOT NULL,
	CONSTRAINT silk_request_pkey PRIMARY KEY (id)
);
CREATE INDEX silk_request_id_5a356c4f_like ON dev.silk_request USING btree (id varchar_pattern_ops);
CREATE INDEX silk_request_path_9f3d798e ON dev.silk_request USING btree (path);
CREATE INDEX silk_request_path_9f3d798e_like ON dev.silk_request USING btree (path varchar_pattern_ops);
CREATE INDEX silk_request_start_time_1300bc58 ON dev.silk_request USING btree (start_time);
CREATE INDEX silk_request_view_name_68559f7b ON dev.silk_request USING btree (view_name);
CREATE INDEX silk_request_view_name_68559f7b_like ON dev.silk_request USING btree (view_name varchar_pattern_ops);


-- dev.auth_permission definition

-- Drop table

-- DROP TABLE dev.auth_permission;

CREATE TABLE dev.auth_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES dev.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON dev.auth_permission USING btree (content_type_id);


-- dev.django_admin_log definition

-- Drop table

-- DROP TABLE dev.django_admin_log;

CREATE TABLE dev.django_admin_log (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id uuid NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES dev.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES dev.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON dev.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON dev.django_admin_log USING btree (user_id);


-- dev.silk_profile definition

-- Drop table

-- DROP TABLE dev.silk_profile;

CREATE TABLE dev.silk_profile (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(300) NOT NULL,
	start_time timestamptz NOT NULL,
	end_time timestamptz NULL,
	time_taken float8 NULL,
	file_path varchar(300) NOT NULL,
	line_num int4 NULL,
	end_line_num int4 NULL,
	func_name varchar(300) NOT NULL,
	exception_raised bool NOT NULL,
	"dynamic" bool NOT NULL,
	request_id varchar(36) NULL,
	CONSTRAINT silk_profile_pkey PRIMARY KEY (id),
	CONSTRAINT silk_profile_request_id_7b81bd69_fk_silk_request_id FOREIGN KEY (request_id) REFERENCES dev.silk_request(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX silk_profile_request_id_7b81bd69 ON dev.silk_profile USING btree (request_id);
CREATE INDEX silk_profile_request_id_7b81bd69_like ON dev.silk_profile USING btree (request_id varchar_pattern_ops);


-- dev.silk_response definition

-- Drop table

-- DROP TABLE dev.silk_response;

CREATE TABLE dev.silk_response (
	id varchar(36) NOT NULL,
	status_code int4 NOT NULL,
	raw_body text NOT NULL,
	body text NOT NULL,
	encoded_headers text NOT NULL,
	request_id varchar(36) NOT NULL,
	CONSTRAINT silk_response_pkey PRIMARY KEY (id),
	CONSTRAINT silk_response_request_id_key UNIQUE (request_id),
	CONSTRAINT silk_response_request_id_1e8e2776_fk_silk_request_id FOREIGN KEY (request_id) REFERENCES dev.silk_request(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX silk_response_id_dda88710_like ON dev.silk_response USING btree (id varchar_pattern_ops);
CREATE INDEX silk_response_request_id_1e8e2776_like ON dev.silk_response USING btree (request_id varchar_pattern_ops);


-- dev.silk_sqlquery definition

-- Drop table

-- DROP TABLE dev.silk_sqlquery;

CREATE TABLE dev.silk_sqlquery (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	query text NOT NULL,
	start_time timestamptz NULL,
	end_time timestamptz NULL,
	time_taken float8 NULL,
	traceback text NOT NULL,
	request_id varchar(36) NULL,
	identifier int4 NOT NULL,
	analysis text NULL,
	CONSTRAINT silk_sqlquery_pkey PRIMARY KEY (id),
	CONSTRAINT silk_sqlquery_request_id_6f8f0527_fk_silk_request_id FOREIGN KEY (request_id) REFERENCES dev.silk_request(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX silk_sqlquery_request_id_6f8f0527 ON dev.silk_sqlquery USING btree (request_id);
CREATE INDEX silk_sqlquery_request_id_6f8f0527_like ON dev.silk_sqlquery USING btree (request_id varchar_pattern_ops);


-- dev.auth_group_permissions definition

-- Drop table

-- DROP TABLE dev.auth_group_permissions;

CREATE TABLE dev.auth_group_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES dev.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES dev.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON dev.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON dev.auth_group_permissions USING btree (permission_id);


-- dev.silk_profile_queries definition

-- Drop table

-- DROP TABLE dev.silk_profile_queries;

CREATE TABLE dev.silk_profile_queries (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	profile_id int4 NOT NULL,
	sqlquery_id int4 NOT NULL,
	CONSTRAINT silk_profile_queries_pkey PRIMARY KEY (id),
	CONSTRAINT silk_profile_queries_profile_id_sqlquery_id_b2403d9b_uniq UNIQUE (profile_id, sqlquery_id),
	CONSTRAINT silk_profile_queries_profile_id_a3d76db8_fk_silk_profile_id FOREIGN KEY (profile_id) REFERENCES dev.silk_profile(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT silk_profile_queries_sqlquery_id_155df455_fk_silk_sqlquery_id FOREIGN KEY (sqlquery_id) REFERENCES dev.silk_sqlquery(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX silk_profile_queries_profile_id_a3d76db8 ON dev.silk_profile_queries USING btree (profile_id);
CREATE INDEX silk_profile_queries_sqlquery_id_155df455 ON dev.silk_profile_queries USING btree (sqlquery_id);
