openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/user/{username}:
    get:
      operationId: api_user_retrieve
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
          description: ''
  /api/users:
    get:
      operationId: api_users_list
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserList'
          description: ''
components:
  schemas:
    UserDetail:
      type: object
      properties:
        password:
          type: string
          title: パスワード
          maxLength: 128
        last_login:
          type: string
          format: date-time
          nullable: true
          title: 最終ログイン
        username:
          type: string
          title: ユーザー名
          maxLength: 20
        email:
          type: string
          format: email
          title: メールアドレス
          maxLength: 254
      required:
      - password
      - username
    UserList:
      type: object
      properties:
        username:
          type: string
          title: ユーザー名
          maxLength: 20
      required:
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
